### ISSUE TITLE
Reply to tweets

### ISSUE THREAD

**Issue by rkdarst** [twitter-together/action#134]
Hi!

As usual, thanks for this action.  I expect a lot of use from it.

I was looking to see how to reply to tweets.  Is the semantics include the URL, or ...?  Perhaps this is obvious to someone who uses twitter a lot, but that's not me... and if it is supported, I can't find the documentation of it in this repo.

Thanks!

**Comment by gr2m** [comment]
It's not supported yet. We would first need to agree on the syntax for a tweet that should reply to an existing one.

There are some other issues open about syntax for tweet attachments, retweets, and threads

**Comment by rkdarst** [comment]
Thanks... that's what I thought, I saw the issue about retweeting, but nothing yet about replying.

I'm not sure if you are looking for suggestions, but my first thought is normal `*.tweet` file with this content:

```
> https://twitter.com/coderefine/status/1311044915602903043

this is the content of the reply
```

First line starts with `>` and then URL or raw tweet ID parsed.  Then rest of body is the content (after removing first line and stripping white space).  At first I thought about a stand-alone URL or ID on first line, but that's more likely to conflict with something someone wants.

Retweet - only the `> ` line and then no body?  Not sure if that makes sense though, or if you'd want to reply to a tweet but have no content.

If someone wanted to start a tweet with `> (id or url pattern)\n` without being a retweet?  Maybe start with a blank line instead?

Just my ideas, I'm no twitter expert and am happy to use whatever.

**Comment by nicolo-ribaudo** [comment]
What about using a custom extension, to avoid any ambiguity?

`foo.reply`

```
https://twitter.com/coderefine/status/1311044915602903043

this is the content of the reply
```

and:

`foo.retweet`

```
https://twitter.com/coderefine/status/1311044915602903043
```

**Comment by s12chung** [comment]
I like @nicolo-ribaudo's idea. @gr2m your thoughts?

**Comment by gr2m** [comment]
I would prefer to have a single specification that accommodates all use cases instead of the different file extensions. See the discussion at https://github.com/gr2m/twitter-together/issues/92

We could introduce something similar to Jekyll's front-matter: https://jekyllrb.com/docs/front-matter/

E.g. 

```
---
type: retweet
tweet: https://twitter.com/coderefine/status/1311044915602903043
---

Optional tweet text here. If present, it will be a quote-tweet, otherwise a retweet.
```

and for replies

```
---
type: reply
tweet: https://twitter.com/coderefine/status/1311044915602903043
---

Reply text here
```

**Comment by gr2m** [comment]
Please see this issue for further discussion: https://github.com/gr2m/twitter-together/issues/166 💖
