### ISSUE TITLE
Write threads

### ISSUE THREAD

**Issue by s12chung** [twitter-together/action#151]
**What’s missing?**

I'd like to add the ability to do threads. Threads will follow the format of: https://getchirrapp.com, where the format of a `.tweet` file is:

```
Contents of tweet 1, which must have 280 characters.

[...]

Each tweet is delimited by:
- the start/end of a file
- `[...]`

[...]

The start and end of the tweet is also stripped of whitespace.

```

**Why?**

I want to tweet threads and I can't do it right now.

**Alternatives you tried**

None. I can attempt to write the code for this later, but I want to have agreement first.

**Comment by vbmendes** [comment]
I really like this idea! Do you need any help on it?

**Comment by gr2m** [comment]
Please see this issue for further discussion: https://github.com/gr2m/twitter-together/issues/166 💖
