### ISSUE TITLE
Use Twitter API v2

### ISSUE THREAD

**Issue by IstoraMandiri** [twitter-together/action#195]
**What happened?**

Perhaps because of twitter deprecating it's v1 API for new twitter account applications, after creating a new tweet, the following error occurs.

```
Run gr2m/twitter-together@v1.x
Running twitter-together version 0.0.0-development
Tweeting: Hello, world!
error
[
  {
    message: 'You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve',
    code: 453
  }
]
```

**What did you expect to happen?**

For simple tweets, it should not need Elevated access.

**What the problem might be**

Support for `twitter-api-v2` node library or some fork of `twitter` that supports v2, rather than `twitter` (updated 5 years ago) which supports v1 only.

**Comment by gr2m** [comment]
I'd very much appreciate any help with upgrading, as much as I wish I could, I can't devote much time to twitter-together right now

**Comment by IstoraMandiri** [comment]
Thanks for the response.

I am considering submitting a PR with a drop-in replacement of the current `twitter` package with [`twitter-lite`](https://github.com/draftbit/twitter-lite) which supports the same JS methods as well as the `v2` API. This should require minimal code changes and maintain compatibility with the draft Front Matter PR.

Sound like a good approach?

**Comment by MattIPv4** [comment]
Adding a note here that moving to the v2 API will allow for using the `polls` object on the status update API, removing the need for calling the Ads API in the code (completely removing the need for the `createPoll` method).

**Comment by MattIPv4** [comment]
Also adding a note that moving to a newer library should unlock the ability for alt text to be added to media (see #177 -- the current `twitter` library does not support the correct payload format).

**Comment by MattIPv4** [comment]
#207
