### ISSUE TITLE
Support multiple twitter accounts 

### ISSUE THREAD

**Issue by IstoraMandiri** [twitter-together/action#209]
**What’s missing?**

The ability to manage multiple twitter accounts from the same repository.

**Why?**

It's common for the same team to manage multiple different twitter handles, for example:

- Multiple languages or regions
- Topic specific accounts (e.g. General News, Support, Development Changelog) 
- Different accounts for importance levels / casualness
- Pseudo anonymous personalities interacting with each other 

**Alternatives you tried**

Instead of having to manage multiple repositories with duplicated code and permissions, it would be easier to be able to specify an optional `account` field in the YAML file, where the tweet will be published to. An alternative would be to use some specific folder structure for each account.

A new config object schema would be required that supports defining multiple accounts.

**Comment by gr2m** [comment]
I fear this would introduce quite a lot of complexity for a rather uncommon use case. And there is a workaround by using multiple repositories. We can leave the issue open to discuss further.

**Comment by IstoraMandiri** [comment]
Yeah, I think you are right about this, and this issue can probably be closed. 

The correct pattern is to create minimal individual repos for each twitter account, pointing to the same action either in this repo or one maintained elsewhere. My confusion came from inheriting the maintenance of a fork of `twitter-together` before it was renamed `action` and my lack of familiarity with github actions.
