### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by 0x3639** [twitter-together/action#244]
**What happened?**
I tried to process a tweet with the tweet-together GH action and the tweet failed and returned this message.

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: twitter-together/action@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

You can see the message here.
https://github.com/zenon-network/twitter/actions/runs/7911741556

**What did you expect to happen?**

I expected it to process a tweet without error.  

**What the problem might be**

Not sure.  I'm using the GH action ad described here.  Ive been tweeting without issue for several months and all of a sudden it stated to fail.  

https://github.com/twitter-together/action?tab=readme-ov-file#setup

**Comment by MattIPv4** [comment]
The run you've linked to didn't fail? Admittedly the report of the deprecation warning is valid, but it is just that, a warning, and does not impact functionality as far as I'm aware.

**Comment by 0x3639** [comment]
That tweet failed to post, but maybe for a different reason.  This was a tweet that was too long (>280 I think).  We corrected the original `.tweet` rather than submitting a new PR.  The GH action does not see the tweet in this case which is why it failed.  

<img width="479" alt="Screenshot 2024-02-18 at 4 07 34 AM" src="https://github.com/twitter-together/action/assets/5406130/7111f990-089e-4ef6-90ee-148356476d18">

**Comment by Piedone** [comment]
@MattIPv4 would you consider updating the Node version still? The deprecation warning is quite annoying, and the update itself seems trivial with just changing "node16" to "node20" in action.yml (hence I didn't submit a PR for it, but we're using the action with success from [a fork](https://github.com/Lombiq/twitter-together-action) with only this changed).

**Comment by MattIPv4** [comment]
Hey! Yeh, I'm happy to accept a PR that bumps the repo to Node.js 20 (I think the .nvmrc file would also need updating). I would be reliant on the tests in the repo though, as I don't think I have a way to test this against X itself anymore with the paid API. I can't see why a Node.js update would be problematic though overly.

**Comment by Piedone** [comment]
Great! I've added an update here: https://github.com/twitter-together/action/pull/247
